# Generated by Django 5.2.5 on 2025-10-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
